src/gz immortalwrt_core https://mirrors.ustc.edu.cn/immortalwrt/releases/24.10/targets/airoha/an7581/packages
src/gz immortalwrt_base https://mirrors.ustc.edu.cn/immortalwrt/releases/24.10/packages/aarch64_cortex-a53/base
src/gz immortalwrt_luci https://mirrors.ustc.edu.cn/immortalwrt/releases/24.10/packages/aarch64_cortex-a53/luci
src/gz immortalwrt_packages https://mirrors.ustc.edu.cn/immortalwrt/releases/24.10/packages/aarch64_cortex-a53/packages
src/gz immortalwrt_routing https://mirrors.ustc.edu.cn/immortalwrt/releases/24.10/packages/aarch64_cortex-a53/routing
