#!/bin/sh

uci set network.lan.ipaddr='192.168.1.1'
uci commit network

uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].flow_offloading_hw='1'
uci commit firewall

echo 300000 > /proc/sys/net/netfilter/nf_conntrack_max

uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
uci commit system

/etc/init.d/network restart

exit 0
